console.log("hi");
setTimeout(function(){console.log("Time Out 2");},2);
console.log("hi");
console.log("hi"); 
console.log("hi");
console.log("hi");
setTimeout(console.log("Time Out 7"),7);
console.log("hi");
console.log("hi");
console.log("hi");
console.log("hi");
setTimeout(console.log("Time Out 3"),3);